### ISSUE TITLE
Cannot find module '!!./../node_modules/css-loader/index.js!./../node_modules/stylus-loader/index.js!./styles.styl'

### ISSUE THREAD

**Issue by prakash-selvam** [vahnag/react-timezone#1]
Getting error:
**build.js:1 Error: Cannot find module '!!./../node_modules/css-loader/index.js!./../node_modules/stylus-loader/index.js!./styles.styl' from '/...../node_modules/react-timezone/build'**

Code:
import React from 'react';
import ReactTimezone from 'react-timezone';
export default class name extends React.Component {

 render() {

    	 
    	 return (<ReactTimezone /> )
}

}

**Comment by vahnag** [comment]
Thanks for reporting. 
It seems like you are using `src/index.js` directly, because there was a typo in `build/` files, which prevented them from working.

Fixed. `0.0.2` is released. The code above will now work.
