### ISSUE TITLE
Webpack warning

### ISSUE THREAD

**Issue by anthonyxiques** [vahnag/react-timezone#18]
Hi there,

Using **react-timezone** in a project and when I run **webpack** this warning is displayed:

![image](https://user-images.githubusercontent.com/3936097/35114967-8d951c2c-fc54-11e7-990e-2cd604f0d588.png)

Any ideas on how to solve? Thank you!

Edit: accidentally wrote "webhook" instead of "webpack"

**Comment by vahnag** [comment]
This should we fixed with the latest release.
