### ISSUE TITLE
Feature Request: Developers should be able to import the list (or object) of timezones from the library

### ISSUE THREAD

**Issue by m-andrew-albright** [vahnag/react-timezone#19]
It is a requirement in my application that the timezone be displayed to the user in the same format as the options appear when selecting `(GMT-06:00) Central Time` for example, instead of `America/Chicago`.

To facilitate this requirement, it would be helpful / beneficial to have the full list of choices that the user has at their disposal when interacting with this component.

Something like 
```js
import TimezonePicker, { timezones } from 'react-timezone';
```

would be ideal.

**Comment by vahnag** [comment]
This is added to the latest release. Thanks!
