### ISSUE TITLE
Is there a reason why is it "Los_Angeles" instead of "Los Angeles"?

### ISSUE THREAD

**Issue by Williamluky** [vahnag/react-timezone#27]
https://github.com/vahnag/react-timezone/blob/64cf512b6b2cdee66a4e257445637b54c7c6ae45/src/timezones.js#L74

**Comment by vahnag** [comment]
That is the timezone format by IANA standard which most of the libraries use for settings timezones. See this: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
