### ISSUE TITLE
Pressing enter submit's the form instead of choosing an option.

### ISSUE THREAD

**Issue by notflip** [vahnag/react-timezone#28]
An idea if it's possible that an enter press chooses an item from the list instead of submitting the form.

**Comment by vahnag** [comment]
Published a new minor version (2.2.0) that stops keyboard event propagation for the ones that are already handled. Additionally you can always customize the behavior with a custom `onKeyDown` handler. Thanks!

**Comment by notflip** [comment]
Thank you very much! It's working perfectly!
