### ISSUE TITLE
Central Time (aka America/Chicago) is being shown as -05:00, should be -06:00

### ISSUE THREAD

**Issue by mike-hewitson** [vahnag/react-timezone#29]
Central Time, which translates to America/Chicago, is being shown as (GMT-05:00 Central Time) in the UI. It The value returned is America/Chicago, which is correct, but is actually -06:00 as far as I can determine. Google calendar also shows Central Time - Chicago as being GMT-06:00.

The UI should show (-06:00 Central Time). I'm very happy to create a PR for this, if you'd like?

**Comment by vahnag** [comment]
I published a new version of the package with the current timezones from Google Calendar. Please check out version `2.3.0`. Thanks!

**Comment by mike-hewitson** [comment]
I will do so and test tomorrow morning. Timezones look fine now in timezones.js

Thanks for the quick fix!

**Comment by mike-hewitson** [comment]
Working 100%, thank's for sorting it out so quickly!
