### ISSUE TITLE
Unable to select timezone in Microsoft Edge 42.17134.1.0

### ISSUE THREAD

**Issue by AbhaysinghBhosale** [vahnag/react-timezone#30]
Found an issue in Edge for timezone selection. Timezone options get loaded but could not select then or search. 

IE mouse click event on option not working in Edge.
Tried this demo in Edge which also having the issue
https://vahnag.github.io/react-timezone/demo/

**Comment by vahnag** [comment]
Thanks for letting me know! This should be fixed in the latest release.

**Comment by vahnag** [comment]
the new version is already released. just update the package to version 2.4.0
