### ISSUE TITLE
Does not work with browserify

### ISSUE THREAD

**Issue by peebles** [vahnag/react-timezone#4]
I use a fairly simple compile for my project:

    browserify --debug -t [ babelify --presets [ es2015 stage-0 react ] ] `find src -name '*.js'` > static/app.built.js

When I "import TimezonePicker from 'react-timezone' I am getting

Error: Cannot find module '!!./../node_modules/css-loader/index.js!./../node_modules/stylus-loader/index.js!./styles.styl' from '/Users/peebles/retailbi2/node_modules/react-timezone/build'

**Comment by vahnag** [comment]
Hi @peebles, fixed with version `0.1.0`.

Please see [CHANGES.md](https://github.com/vahnag/react-timezone/blob/master/CHANGES.md) and updated [README.md](https://github.com/vahnag/react-timezone/blob/master/README.md).

Thank you for you issue.
