### ISSUE TITLE
Add ability to provide your own set of timezones

### ISSUE THREAD

**Issue by venil7** [vahnag/react-timezone#7]
at the moment its hardcoded to set of timezones (and their labels) 

for example for London it shows GMT+0:00, which is not technically correct during Summer British Time

**Comment by vahnag** [comment]
Hi @venil7, added `timezones` prop in version `0.1.0`.

Please see [CHANGES.md](https://github.com/vahnag/react-timezone/blob/master/CHANGES.md) and updated [README.md](https://github.com/vahnag/react-timezone/blob/master/README.md).

Thank you for you issue.

**Comment by venil7** [comment]
👍

**Comment by AnthonyCrowcroft** [comment]
is this still possible to load a custom list of timezones in as I can't find mention of it on the README.md
